# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = ["kvm-amd" "amdgpu"];
  boot.extraModulePackages = [];
  boot.supportedFilesystems = [
    "ntfs"
    "btrfs"
    "ext4"
    "ext3"
    "exfat"
    "fat32"
  ];

  # boot.kernelPackages = pkgs.linuxPackages_latest;
  # es8336 patches from https://github.com/codepayne/pop-os-linux
  # boot.kernelPatches = [
  #   {
  #     name = "es8336 support";
  #     patch = "${./es8336.patch}";
  #   }
  # ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9ee038a0-936b-4c23-bf07-b920e3cd10f1";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F1F3-BB35";
      fsType = "vfat";
    };

  swapDevices = [ { device = "/dev/disk/by-uuid/ac643373-d2b0-44f1-8d83-f2358db66c3d"; }];


  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.enableRedistributableFirmware = true;
  hardware.xpadneo.enable = true;
}
